import React, { useCallback, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, ActivityIndicator, RefreshControl, Pressable } from 'react-native';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { FieldMeshColors, FieldMeshSpacing, FieldMeshRadius } from '@/constants/fieldMeshTheme';
import { FieldMeshHeader } from '@/components/fieldmesh/FieldMeshHeader';
import { FieldMeshIcon } from '@/components/fieldmesh/FieldMeshIcon';
import { PhotoThumb } from '@/components/fieldmesh/PhotoThumb';
import { CHECKLIST_TEMPLATE } from '@/constants/checklistTemplate';
import { useAuth } from '@/lib/auth-context';
import { api, errorMessage, type Report } from '@/lib/api';
import { displayValue, fieldTitle, formatTime, isHiddenField } from '@/lib/checklist';
import { isPhotoHash } from '@/lib/photos';
import { nameFor } from '@/lib/names';

/** GET /inspections/:id/report — the server's fold of the edit log per field, plus verified photos. */
export default function ReportScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { user } = useAuth();
  const [report, setReport] = useState<Report | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async () => {
    if (!id) return;
    try {
      setReport(await api.report(id));
      setError(null);
    } catch (e) {
      setError(errorMessage(e));
    }
  }, [id]);

  useFocusEffect(
    useCallback(() => {
      load();
    }, [load])
  );

  const onRefresh = async () => {
    setRefreshing(true);
    await load();
    setRefreshing(false);
  };

  const name = (authorId: string) => nameFor(authorId, user && authorId === user.id ? user.name : undefined);

  // Template order first, then any other field ids the server reports.
  const fieldIds = report
    ? [
        ...CHECKLIST_TEMPLATE.map((f) => f.fieldId),
        ...Object.keys(report.fields).filter((k) => !CHECKLIST_TEMPLATE.some((f) => f.fieldId === k) && !isHiddenField(k)),
      ]
    : [];
  const hiddenIds = report ? Object.keys(report.fields).filter(isHiddenField) : [];

  return (
    <View style={styles.container}>
      <FieldMeshHeader
        title="Inspection Report"
        category="REPORT"
        showBack
        statusBadge={
          report
            ? report.summary.disputedFields > 0
              ? { label: `${report.summary.disputedFields} disputed`, variant: 'warning' }
              : { label: 'Signed off', variant: 'connected' }
            : { label: 'Loading…', variant: 'offline' }
        }
      />
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 32 }]}
        showsVerticalScrollIndicator={false}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}
      >
        {error && (
          <View style={styles.errorBanner}>
            <FieldMeshIcon name="cloud_off" size={16} color={FieldMeshColors.onErrorContainer} />
            <Text style={styles.errorBannerText}>{error} Reports are generated by the server.</Text>
          </View>
        )}
        {!report ? (
          !error && <ActivityIndicator style={{ marginTop: 40 }} color={FieldMeshColors.primary} />
        ) : (
          <>
            <View style={styles.headerCard}>
              <Text style={styles.code}>#{report.inspection.id.slice(-6).toUpperCase()} · schema v{report.inspection.schema_version}</Text>
              <Text style={styles.title}>{report.inspection.title}</Text>
              {report.inspection.site ? <Text style={styles.subtitle}>{report.inspection.site}</Text> : null}
              <Text style={styles.generated}>
                Generated {formatTime(report.generatedAt)} · created by {name(report.inspection.created_by)}
              </Text>
            </View>

            <View style={styles.summaryRow}>
              <SummaryTile label="Edits" value={report.summary.edits} />
              <SummaryTile label="Fields" value={report.summary.fields} />
              <SummaryTile label="Disputed" value={report.summary.disputedFields} warn={report.summary.disputedFields > 0} />
              <SummaryTile label="Photos" value={report.summary.photos} />
            </View>

            <Text style={styles.sectionLabel}>FIELDS</Text>
            <View style={styles.list}>
              {fieldIds.map((fieldId) => {
                const f = report.fields[fieldId];
                const template = CHECKLIST_TEMPLATE.find((t) => t.fieldId === fieldId);
                const value = f?.value ?? null;
                return (
                  <View key={fieldId} style={[styles.fieldRow, f?.disputed && styles.fieldRowDisputed]}>
                    <View style={{ flex: 1 }}>
                      <Text style={styles.fieldTitle}>{template?.title ?? fieldTitle(fieldId)}</Text>
                      <Text style={styles.fieldValue}>
                        {value === null
                          ? 'Not recorded'
                          : isPhotoHash(value)
                            ? `Photo ${value.slice(0, 10)}…`
                            : `${displayValue(value)}${template?.unit && template.type === 'numeric' ? template.unit : ''}`}
                      </Text>
                      {f && (
                        <Text style={styles.fieldMeta}>
                          {name(f.lastEditedBy)} · {formatTime(f.lastEditedAt)} · {f.edits} edit{f.edits === 1 ? '' : 's'}
                          {f.heads.length > 1 ? ` · ${f.heads.length} heads` : ''}
                        </Text>
                      )}
                      {f?.disputed && (
                        <Pressable onPress={() => router.push({ pathname: '/(fieldmesh)/inspections/dispute', params: { id: id ?? '', fieldId } })}>
                          <Text style={styles.resolveLink}>Open dispute →</Text>
                        </Pressable>
                      )}
                    </View>
                    {isPhotoHash(value) ? (
                      <PhotoThumb hash={value} size={44} />
                    ) : (
                      <FieldMeshIcon
                        name={f?.disputed ? 'warning' : value !== null ? 'check_circle' : 'schedule'}
                        size={20}
                        color={f?.disputed ? FieldMeshColors.tertiary : value !== null ? FieldMeshColors.secondary : FieldMeshColors.outline}
                      />
                    )}
                  </View>
                );
              })}
            </View>

            {hiddenIds.length > 0 && (
              <>
                <Text style={styles.sectionLabel}>RESOLUTION NOTES</Text>
                <View style={styles.list}>
                  {hiddenIds.map((fieldId) => (
                    <View key={fieldId} style={styles.noteRow}>
                      <FieldMeshIcon name="edit_note" size={18} color={FieldMeshColors.primary} />
                      <View style={{ flex: 1 }}>
                        <Text style={styles.fieldValue}>{report.fields[fieldId].value}</Text>
                        <Text style={styles.fieldMeta}>
                          {name(report.fields[fieldId].lastEditedBy)} · {formatTime(report.fields[fieldId].lastEditedAt)}
                        </Text>
                      </View>
                    </View>
                  ))}
                </View>
              </>
            )}

            <Text style={styles.sectionLabel}>VERIFIED PHOTOS ({report.photos.length})</Text>
            {report.photos.length === 0 ? (
              <Text style={styles.emptyText}>No photos uploaded for this inspection.</Text>
            ) : (
              <View style={styles.photoGrid}>
                {report.photos.map((p) => (
                  <View key={p.hash} style={styles.photoCard}>
                    <PhotoThumb hash={p.hash} size={96} />
                    <Text style={styles.photoMeta} numberOfLines={1}>
                      {(p.size / 1024).toFixed(0)} KB · {name(p.uploadedBy)}
                    </Text>
                    <Text style={styles.photoHash} numberOfLines={1}>
                      {p.hash.slice(0, 16)}…
                    </Text>
                  </View>
                ))}
              </View>
            )}
          </>
        )}
      </ScrollView>
    </View>
  );
}

function SummaryTile({ label, value, warn }: { label: string; value: number; warn?: boolean }) {
  return (
    <View style={[styles.tile, warn && styles.tileWarn]}>
      <Text style={[styles.tileValue, warn && styles.tileValueWarn]}>{value}</Text>
      <Text style={styles.tileLabel}>{label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: FieldMeshColors.surface },
  scroll: { flex: 1 },
  content: { padding: FieldMeshSpacing.gutter, gap: FieldMeshSpacing.md },
  errorBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: FieldMeshColors.errorContainer, padding: 10, borderRadius: FieldMeshRadius.md },
  errorBannerText: { flex: 1, fontSize: 12, fontWeight: '600', color: FieldMeshColors.onErrorContainer },
  headerCard: { gap: 4 },
  code: { fontFamily: 'monospace', fontSize: 11, fontWeight: '700', color: FieldMeshColors.onSurfaceVariant },
  title: { fontSize: 20, fontWeight: '700', color: FieldMeshColors.onSurface },
  subtitle: { fontSize: 13, color: FieldMeshColors.onSurfaceVariant },
  generated: { fontSize: 11, fontFamily: 'monospace', color: FieldMeshColors.outline, marginTop: 4 },
  summaryRow: { flexDirection: 'row', gap: 8 },
  tile: { flex: 1, backgroundColor: FieldMeshColors.surfaceContainerLow, borderRadius: FieldMeshRadius.md, padding: 10, alignItems: 'center', gap: 2 },
  tileWarn: { backgroundColor: FieldMeshColors.tertiaryFixed },
  tileValue: { fontSize: 20, fontWeight: '700', color: FieldMeshColors.onSurface, fontFamily: 'monospace' },
  tileValueWarn: { color: FieldMeshColors.onTertiaryFixed },
  tileLabel: { fontSize: 10, fontWeight: '700', color: FieldMeshColors.onSurfaceVariant, textTransform: 'uppercase' },
  sectionLabel: { fontSize: 11, fontWeight: '700', color: FieldMeshColors.outline, letterSpacing: 0.5, marginTop: 4 },
  list: { gap: 8 },
  fieldRow: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: FieldMeshColors.surfaceLowest, borderRadius: FieldMeshRadius.md, padding: 12, borderWidth: 1, borderColor: FieldMeshColors.surfaceContainerHigh },
  fieldRowDisputed: { borderColor: FieldMeshColors.tertiaryContainer, backgroundColor: FieldMeshColors.tertiaryFixed },
  fieldTitle: { fontSize: 13.5, fontWeight: '700', color: FieldMeshColors.onSurface },
  fieldValue: { fontSize: 12.5, color: FieldMeshColors.onSurface, marginTop: 2 },
  fieldMeta: { fontSize: 10.5, color: FieldMeshColors.outline, marginTop: 3, fontFamily: 'monospace' },
  resolveLink: { fontSize: 12, fontWeight: '700', color: FieldMeshColors.onTertiaryFixedVariant, marginTop: 4 },
  noteRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, backgroundColor: FieldMeshColors.surfaceContainerLow, borderRadius: FieldMeshRadius.md, padding: 12 },
  emptyText: { fontSize: 12, color: FieldMeshColors.onSurfaceVariant },
  photoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  photoCard: { width: 96, gap: 3 },
  photoMeta: { fontSize: 10, color: FieldMeshColors.onSurfaceVariant },
  photoHash: { fontFamily: 'monospace', fontSize: 9, color: FieldMeshColors.outline },
});
